// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHexFJE-pgYcYugN9obTeYsJZOjKqAGv0',
    appId: '1:967632206782:web:d5d2531c5e954ea77d17ef',
    messagingSenderId: '967632206782',
    projectId: 'gamifier-ca201',
    authDomain: 'gamifier-ca201.firebaseapp.com',
    storageBucket: 'gamifier-ca201.firebasestorage.app',
    measurementId: 'G-6KLNQM3T8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAu54WnBbXzkyGU3yqP_LCZ9CadDIM_o',
    appId: '1:967632206782:android:d5207456b47ef0767d17ef',
    messagingSenderId: '967632206782',
    projectId: 'gamifier-ca201',
    storageBucket: 'gamifier-ca201.firebasestorage.app',
  );

}